// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/rhodamineb13/backend-test/models/dtos"
	mock "github.com/stretchr/testify/mock"
)

// ICategoryService is an autogenerated mock type for the ICategoryService type
type ICategoryService struct {
	mock.Mock
}

// GetCategoryByID provides a mock function with given fields: ctx, id
func (_m *ICategoryService) GetCategoryByID(ctx context.Context, id uint) (*dtos.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *dtos.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*dtos.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *dtos.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertNewCategory provides a mock function with given fields: ctx, data
func (_m *ICategoryService) InsertNewCategory(ctx context.Context, data dtos.Category) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InsertNewCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.Category) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListCategories provides a mock function with given fields: ctx
func (_m *ICategoryService) ListCategories(ctx context.Context) ([]dtos.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []dtos.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dtos.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dtos.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICategoryService creates a new instance of ICategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICategoryService {
	mock := &ICategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
