// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/rhodamineb13/backend-test/models/entities"
	mock "github.com/stretchr/testify/mock"
)

// ICategoryRepository is an autogenerated mock type for the ICategoryRepository type
type ICategoryRepository struct {
	mock.Mock
}

// GetCategoryByID provides a mock function with given fields: ctx, id
func (_m *ICategoryRepository) GetCategoryByID(ctx context.Context, id uint) (*entities.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *entities.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertNewCategory provides a mock function with given fields: ctx, data
func (_m *ICategoryRepository) InsertNewCategory(ctx context.Context, data entities.Category) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InsertNewCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Category) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListCategories provides a mock function with given fields: ctx
func (_m *ICategoryRepository) ListCategories(ctx context.Context) ([]entities.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []entities.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICategoryRepository creates a new instance of ICategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICategoryRepository {
	mock := &ICategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
