// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/rhodamineb13/backend-test/models/entities"
	mock "github.com/stretchr/testify/mock"
)

// IProductRepository is an autogenerated mock type for the IProductRepository type
type IProductRepository struct {
	mock.Mock
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *IProductRepository) DeleteProduct(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *IProductRepository) GetProductByID(ctx context.Context, id uint) (*entities.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *entities.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertNewProduct provides a mock function with given fields: ctx, data
func (_m *IProductRepository) InsertNewProduct(ctx context.Context, data entities.Product) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InsertNewProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Product) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListProducts provides a mock function with given fields: ctx, name, category, price, stockQuantity, limit, page
func (_m *IProductRepository) ListProducts(ctx context.Context, name string, category uint, price float32, stockQuantity uint, limit uint, page uint) (*entities.DashboardProduct, error) {
	ret := _m.Called(ctx, name, category, price, stockQuantity, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 *entities.DashboardProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, float32, uint, uint, uint) (*entities.DashboardProduct, error)); ok {
		return rf(ctx, name, category, price, stockQuantity, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, float32, uint, uint, uint) *entities.DashboardProduct); ok {
		r0 = rf(ctx, name, category, price, stockQuantity, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DashboardProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, float32, uint, uint, uint) error); ok {
		r1 = rf(ctx, name, category, price, stockQuantity, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, id, data
func (_m *IProductRepository) UpdateProduct(ctx context.Context, id uint, data entities.Product) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, entities.Product) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIProductRepository creates a new instance of IProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProductRepository {
	mock := &IProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
