// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/rhodamineb13/backend-test/models/dtos"
	mock "github.com/stretchr/testify/mock"
)

// IProductService is an autogenerated mock type for the IProductService type
type IProductService struct {
	mock.Mock
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *IProductService) DeleteProduct(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *IProductService) GetProductByID(ctx context.Context, id uint) (*dtos.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *dtos.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*dtos.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *dtos.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertNewProduct provides a mock function with given fields: ctx, data
func (_m *IProductService) InsertNewProduct(ctx context.Context, data dtos.Product) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InsertNewProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.Product) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListProducts provides a mock function with given fields: ctx, name, category, price, stock_quantity, limit, offset
func (_m *IProductService) ListProducts(ctx context.Context, name string, category uint, price float32, stock_quantity uint, limit uint, offset uint) (*dtos.ProductResponse, error) {
	ret := _m.Called(ctx, name, category, price, stock_quantity, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 *dtos.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, float32, uint, uint, uint) (*dtos.ProductResponse, error)); ok {
		return rf(ctx, name, category, price, stock_quantity, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, float32, uint, uint, uint) *dtos.ProductResponse); ok {
		r0 = rf(ctx, name, category, price, stock_quantity, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, float32, uint, uint, uint) error); ok {
		r1 = rf(ctx, name, category, price, stock_quantity, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, id, data
func (_m *IProductService) UpdateProduct(ctx context.Context, id uint, data dtos.Product) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, dtos.Product) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIProductService creates a new instance of IProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProductService {
	mock := &IProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
